apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: identity-route-config
spec:
  routes:
  - order: 0
    ssoEnabled: true
    predicates:
    - Path=/acme-login
    - Method=GET
    filters:
    - RedirectTo=302, /
    tags:
    - sso
  - ssoEnabled: true
    tokenRelay: true
    predicates:
    - Path=/userinfo
    - Method=GET
    filters:
    - RedirectTo=302, /whoami
    - SetResponseHeader=Cache-Control, no-store
    tags:
    - users
  - uri: no://op
    predicates:
    - Path=/verify-token
    - Method=POST
    ssoEnabled: true
    tags:
    - users
  - ssoEnabled: true
    tokenRelay: true
    predicates:
    - Path=/whoami
    - Method=GET
    filters:
    - StripPrefix=0
    tags:
    - users
  service:
    name: acme-identity
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: identity-route-mapping
spec:
  gatewayRef:
    name: acme-fitness-gateway
  routeConfigRef:
    name: identity-route-config