apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: order-route-config
spec:
  routes:
  - ssoEnabled: true
    tokenRelay: true
    title: Create an order.
    description: Creates an order for the user.
    predicates:
    - Path=/order/add/{userId}
    - Method=POST
    filters:
    - StripPrefix=0
    tags:
    - order
  - ssoEnabled: true
    tokenRelay: true
    title: Retrieve User's Orders.
    description: Lookup all orders for the given user
    predicates:
    - Path=/order/{userId}
    - Method=GET
    filters:
    - StripPrefix=0
    tags:
    - order
  service:
    name: acme-order
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: order-route-mapping
spec:
  gatewayRef:
    name: acme-fitness-gateway
  routeConfigRef:
    name: order-route-config